### ISSUE TITLE
Laravel 8  publish provider

### ISSUE THREAD

**Issue by eliassdogos** [litespeedtech/lscache-laravel#16]
Hi,
For laravel 8 the command "php artisan vendor:publish --provider="Litespeed\LSCache\LSCacheServiceProvider""  produces config cache. I set group middleware 
Route::group(['prefix' => 'admin', 'middleware' => ['lscache:no-cache', 'lstags:admin']], function () {
routes....

But i have proble with images update. The image is vissible after 3,4 times reload. 
Also i have pagespeed apache.

Any comment?

**Comment by lucasRolff** [comment]
> For laravel 8 the command "php artisan vendor:publish --provider="Litespeed\LSCache\LSCacheServiceProvider"" produces config cache

`vendor:publish` will add `config/lscache.php` - that's all it should do.

> But i have proble with images update. The image is vissible after 3,4 times reload.
> Also i have pagespeed apache.

lscache does not handle images, css and javascript. It only caches PHP pages (in Laravel the routes you define) - if you have to refresh 3-4 times for image updates to appear, then it's likely coming from mod_pagespeed.
