### ISSUE TITLE
LiteSpeed Cache and Browser Cache

### ISSUE THREAD

**Issue by eliassdogos** [litespeedtech/lscache-laravel#18]
LiteSpeed Cache and Browser Cache. are different thing.

LiteSpeed Cache Rules at web.php (laravel) ovverides Browser cache(defaults or rules from headers via php) or not?

**Comment by lucasRolff** [comment]
They're not related. What LiteSpeed Cache rules you set doesn't affect your browser cache, and neither does it the other way around.

They're handling two different layers (one being on the server, and one being in the browser).

**Comment by eliassdogos** [comment]
I mean response headers.
For example here https://imgur.com/e9XiXQd
Cache-Control: is affected from litespeed cache rules which has been hit?

**Comment by lucasRolff** [comment]
The Cache-Control header is not affected or set by the lscache plugin for Laravel. The Cache-Control header controls browser cache, not server cache.
