### ISSUE TITLE
Private caching without ESI

### ISSUE THREAD

**Issue by binaryfire** [litespeedtech/lscache-laravel#23]
Hi guys,

Someone on Slack mentioned private caching won't work without ESI. I'm using OpenLiteSpeed so I won't be able to use ESI.

Is there any way to work around this? I'm moving from WordPress to Laravel and have been enjoying private caching on OLS via the WordPress LSCache plugin.

I'd prefer not to lose that if possible!

Cheers

**Comment by lucasRolff** [comment]
You can use private caching without ESI as long as the webserver supports it. The Laravel lscache package does not have any logic that would prevent this.

**Comment by binaryfire** [comment]
@lucasRolff Great! That's what I suspected. Thanks for confirming
