### ISSUE TITLE
Purging multiple (or at least two) slugs

### ISSUE THREAD

**Issue by darkponyhq** [litespeedtech/lscache-laravel#6]
Hi,

We are trying to purge single articles + the homepage of a website upon updating a single article.

Having:

```
LSCache::purge('/an-article-slug'); // the article we update
LSCache::purge('/'); // the homepage 
```

does not work since headers are already send.

Is it possible to have purge extended in order to support multiple slugs (similar to multiple tags)

e.g.

`LSCache::purge('/slug1', '/slug2', .... )`

Thanks

**Comment by lucasRolff** [comment]
You can simply do:

```php
LSCache::purge('/an-article-slug,/');
```

That will purge both entries.

You can also assign your pages tags using `lstags` and purge based on this.

**Comment by darkponyhq** [comment]
Fantastic, 

why don't you add this to the documentation? 

TA

**Comment by lucasRolff** [comment]
It has been added to the README file.
